package dev.magaiver.eventcheckin.api;

public class Routes {

    public static final String URL_BASE = "http://192.168.0.18:5005/gateway";
    public static final String URL_EVENT = "/subscription/v1/event/";
    public static final String URL_CHECK_IN = "/subscription/v1/event/";
    public static final String URL_USER = "/user-service/v1/user";
    public static final String URL_SUBSCRIBE = "/subscription/v1/subscription";
    public static final String URL_CANCEL_SUB = "/subscription/v1/subscription/cancel";

    // TODO Authenticate in backend
    public static final String TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsImtpZCI6ImMzNWUyMmZlLTYzMjItNGUyOS04YzQ2LTQyNDhhNGQ4ZjE5YyIsIm4iOiJseTNyV1dRemxIMGcybjBpOHBnUnpZUDBNZlVlUGVFQXNhWFZFYlZ2WmpUUERTUXF6aFBLQ0FOUU9GMHp0TkRXeXJWUzc3VERjejExcTVGMWpxWDJVM2t0VTJNWXZlUHJWMElVTVhvV1pzT2RkZ1pjbTlLODJQNFZnWXhMYTN6OEZxM1dsc0VxZEVoOHRLTTVhTW5uamdLZUxlWlI2UEtQdjJQa0lkUHZEUVJ1UGdBbi16TWhIUFM0cmxBaXZROE15TG1DWXBlbHBCbmNRUFlaOGw2bVdOeWhnREtVT1E5bkVaRXZRblo3NTAwbllWc1A2RndlQVNoN2o0MS1FWUlvWHFkdzdvV0ZUQUdodENwNTVnRDBXV1JBZUpoektTZDhqSHdjb3JJWTljQURSNUl0aGdaMlJtekNGOWZoRFRwUFJEd3Z1QmVZNmJ6Y3JPRGEwclM2NVEifX0.eyJzdWIiOiJtYWdhaXdlckBob3RtYWlsLmNvbS5iciIsImV4cCI6MTY3NDQ2MTEzOCwiaWF0IjoxNjM4NDYxMTM4LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.d3w-GiN_gd76Uq-vX7E0Wn_atq6Gg3qeTgLVWTGrQ8nqjH8NzhuQBL-nsRerGRFiH5dEkAfT2Ztcwx-yuIzkdBIS4EJy3NHCvOARpqwdZ0Rms5JEtFQbM6qvnD6SmrhAVFJ3obQCW0ZCmyq_vNE7cVLjttJ6_t8TwG6tUQ2aYv1xnXOSuD82yXHcL0lmFG70UV5PYxt0ACzAJPHmFSfbBzf9qZ0i39oy-DVR5pJCgTiTX_gHr5PU59wZz5Rx8-WaKjPNedK1GMrlFxoR0T5VKnhXqUKoDyvwFNvxcLBcTufRmrcDIWV8U9h_Q9tNbQdCNxiKEiSIgyKBQkpS9f1dHg";
}
